name: trigger jenkins job
on: [push]
jobs:
  jenkins-container-pipeline:
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: jenkinsci/jfr-setup-action@master
      - uses: jenkinsci/jfr-plugin-installation-action@master
        with:
          pluginstxt: plugins.txt
      - uses: jenkinsci/jfr-runtime-action@master
        with:
          command: run
          jenkinsfile: Jenkinsfile
